import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

// Client-side config generated by the environment setup
const firebaseConfig = {
  apiKey: "AIzaSyA8s1ymnemwisxKwvS9DHwsxZ-o7a4WP4s",
  authDomain: "spotua.firebaseapp.com",
  projectId: "spotua",
  storageBucket: "spotua.firebasestorage.app",
  messagingSenderId: "1083634982348",
  appId: "1:1083634982348:web:3319170ad4e626abb31169",
  measurementId: "G-C5DBX0HERV"

};

const app = initializeApp(firebaseConfig);

// Initialize Firestore with the custom database ID from firebase-applet-config.json
export const db = getFirestore(app, "ai-studio-spotua-b8bcfd5f-5a3a-44e4-b5f8-d8c4b4e08d0f");
